# """
# LaneLogic - PERSON 3: Backend/API
# ====================================
# Role in the pipeline: the "plumbing" connecting every module.

# Run:
#   uvicorn main:app --reload --port 8000

# Docs (auto-generated by FastAPI):
#   http://localhost:8000/docs

# Endpoints:
#   POST /roads                          - register/update a road (metadata for the map)
#   GET  /roads                          - list all roads with current status (for GIS map + dashboard)
#   GET  /roads/{road_id}                - full detail: recent observations, chronic flag, recommendations
#   POST /detections/bulk                - ingest Person 1's raw detections
#   POST /analysis/bulk                  - ingest Person 2's window-level occupancy/cause analysis
#                                           (also updates the road's live status)
#   GET  /roads/{road_id}/history        - full observation history for a road (History page)
#   POST /chronic-zones/bulk             - ingest Person 4's chronic-zone flags
#   GET  /chronic-zones                  - list all chronic zones
#   POST /recommendations/bulk           - ingest Person 4's recommendations
#   GET  /recommendations                - list all recommendations (optionally filter by road_id)
# """

# from typing import Optional, List

# from fastapi import FastAPI, Depends, HTTPException, Query
# from fastapi.middleware.cors import CORSMiddleware
# from sqlalchemy.orm import Session

# import models
# import schemas
# from database import engine, get_db

# models.Base.metadata.create_all(bind=engine)

# app = FastAPI(title="LaneLogic API", version="1.0.0")

# # Allow the Vite dev server (Person 6 frontend) to call this API directly.
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_credentials=True,
#     allow_methods=["*"],
#     allow_headers=["*"],
# )


# def status_from_pcts(occupancy_pct: float, blocked_pct: float) -> str:
#     """
#     Explainable, rule-based status color used across the map + dashboard.
#       RED (severe)    : blocked_pct >= 40  OR occupancy_pct >= 70
#       YELLOW (moderate): blocked_pct >= 15  OR occupancy_pct >= 40
#       GREEN (normal)  : otherwise
#     """
#     if blocked_pct >= 40 or occupancy_pct >= 70:
#         return "severe"
#     if blocked_pct >= 15 or occupancy_pct >= 40:
#         return "moderate"
#     return "normal"


# # ---------------------------------------------------------------------------
# # Roads
# # ---------------------------------------------------------------------------

# @app.post("/roads", response_model=schemas.RoadOut)
# def upsert_road(road: schemas.RoadCreate, db: Session = Depends(get_db)):
#     existing = db.get(models.Road, road.id)
#     if existing:
#         existing.name = road.name
#         existing.latitude = road.latitude
#         existing.longitude = road.longitude
#         existing.polygon_geojson = road.polygon_geojson
#         db.commit()
#         db.refresh(existing)
#         return existing

#     new_road = models.Road(
#         id=road.id,
#         name=road.name,
#         latitude=road.latitude,
#         longitude=road.longitude,
#         polygon_geojson=road.polygon_geojson,
#     )
#     db.add(new_road)
#     db.commit()
#     db.refresh(new_road)
#     return new_road


# @app.get("/roads", response_model=List[schemas.RoadOut])
# def list_roads(db: Session = Depends(get_db)):
#     roads = db.query(models.Road).all()
#     return [
#         schemas.RoadOut(
#             id=r.id, name=r.name, latitude=r.latitude, longitude=r.longitude,
#             polygon_geojson=r.polygon_geojson, current_status=r.current_status,
#             current_occupancy_pct=r.current_occupancy_pct,
#             current_dominant_cause=r.current_dominant_cause,
#             is_chronic=bool(r.is_chronic),
#         )
#         for r in roads
#     ]


# @app.get("/roads/{road_id}", response_model=schemas.RoadDetailOut)
# def road_detail(road_id: str, db: Session = Depends(get_db)):
#     road = db.get(models.Road, road_id)
#     if not road:
#         raise HTTPException(status_code=404, detail="Road not found")

#     recent_obs = (
#         db.query(models.RoadWindowObservation)
#         .filter(models.RoadWindowObservation.road_id == road_id)
#         .order_by(models.RoadWindowObservation.window_index.desc())
#         .limit(20)
#         .all()
#     )
#     chronic = (
#         db.query(models.ChronicZone)
#         .filter(models.ChronicZone.road_id == road_id)
#         .first()
#     )
#     recs = (
#         db.query(models.Recommendation)
#         .filter(models.Recommendation.road_id == road_id)
#         .order_by(models.Recommendation.priority_rank.asc())
#         .all()
#     )

#     return schemas.RoadDetailOut(
#         road=schemas.RoadOut(
#             id=road.id, name=road.name, latitude=road.latitude, longitude=road.longitude,
#             polygon_geojson=road.polygon_geojson, current_status=road.current_status,
#             current_occupancy_pct=road.current_occupancy_pct,
#             current_dominant_cause=road.current_dominant_cause,
#             is_chronic=bool(road.is_chronic),
#         ),
#         recent_observations=recent_obs,
#         chronic_zone=chronic,
#         recommendations=recs,
#     )


# @app.get("/roads/{road_id}/history", response_model=List[schemas.ObservationOut])
# def road_history(road_id: str, db: Session = Depends(get_db)):
#     obs = (
#         db.query(models.RoadWindowObservation)
#         .filter(models.RoadWindowObservation.road_id == road_id)
#         .order_by(models.RoadWindowObservation.window_index.asc())
#         .all()
#     )
#     return obs


# # ---------------------------------------------------------------------------
# # Ingestion from Person 1 (raw detections) and Person 2 (window analysis)
# # ---------------------------------------------------------------------------

# @app.post("/detections/bulk")
# def ingest_detections(payload: schemas.DetectionsBulkIn, db: Session = Depends(get_db)):
#     rows = [models.VehicleDetection(**d.model_dump()) for d in payload.detections]
#     db.add_all(rows)
#     db.commit()
#     return {"inserted": len(rows)}


# @app.post("/analysis/bulk")
# def ingest_analysis(payload: schemas.ObservationsBulkIn, db: Session = Depends(get_db)):
#     rows = []
#     for obs in payload.observations:
#         rows.append(models.RoadWindowObservation(**obs.model_dump()))

#     db.add_all(rows)
#     db.commit()

#     # Update each affected road's denormalized "current status" using its
#     # latest window so the map/dashboard can read a single row.
#     latest_by_road = {}
#     for obs in payload.observations:
#         prev = latest_by_road.get(obs.road_id)
#         if prev is None or obs.window_index > prev.window_index:
#             latest_by_road[obs.road_id] = obs

#     for road_id, obs in latest_by_road.items():
#         road = db.get(models.Road, road_id)
#         if road is None:
#             continue
#         road.current_status = status_from_pcts(obs.occupancy_pct, obs.blocked_pct)
#         road.current_occupancy_pct = obs.occupancy_pct
#         road.current_dominant_cause = obs.cause
#     db.commit()

#     return {"inserted": len(rows)}


# # ---------------------------------------------------------------------------
# # Person 4 (recurrence + recommendations) ingestion & read endpoints
# # ---------------------------------------------------------------------------

# @app.post("/chronic-zones/bulk")
# def ingest_chronic_zones(zones: List[schemas.ChronicZoneIn], db: Session = Depends(get_db)):
#     count = 0
#     for z in zones:
#         existing = (
#             db.query(models.ChronicZone)
#             .filter(models.ChronicZone.road_id == z.road_id)
#             .first()
#         )
#         if existing:
#             existing.dominant_cause = z.dominant_cause
#             existing.occurrence_count = z.occurrence_count
#             existing.severity_score = z.severity_score
#             existing.notes = z.notes
#         else:
#             db.add(models.ChronicZone(**z.model_dump()))
#         road = db.get(models.Road, z.road_id)
#         if road:
#             road.is_chronic = 1
#         count += 1
#     db.commit()
#     return {"upserted": count}


# @app.get("/chronic-zones", response_model=List[schemas.ChronicZoneOut])
# def list_chronic_zones(db: Session = Depends(get_db)):
#     return db.query(models.ChronicZone).order_by(models.ChronicZone.severity_score.desc()).all()


# @app.post("/recommendations/bulk")
# def ingest_recommendations(recs: List[schemas.RecommendationIn], db: Session = Depends(get_db)):
#     rows = [models.Recommendation(**r.model_dump()) for r in recs]
#     db.add_all(rows)
#     db.commit()
#     return {"inserted": len(rows)}


# @app.get("/recommendations", response_model=List[schemas.RecommendationOut])
# def list_recommendations(road_id: Optional[str] = Query(default=None), db: Session = Depends(get_db)):
#     q = db.query(models.Recommendation)
#     if road_id:
#         q = q.filter(models.Recommendation.road_id == road_id)
#     return q.order_by(models.Recommendation.priority_rank.asc()).all()


# @app.get("/")
# def root():
#     return {"service": "LaneLogic API", "status": "ok"}













"""
LaneLogic - PERSON 3: Backend/API
====================================

Role:
    Backend/API connecting Person 1, Person 2,
    Person 4, Person 5 and Person 6.

Pipeline:

    Person 1
        ↓
    /detections/bulk
        ↓
    Person 2
        ↓
    /analysis/bulk
        ↓
    SQLite
        ↓
    Person 4 / Person 5 / Person 6

Run:

    uvicorn main:app --reload --port 8000

Docs:

    http://localhost:8000/docs
"""

from typing import Optional, List

from fastapi import (
    FastAPI,
    Depends,
    HTTPException,
    Query
)

from fastapi.middleware.cors import CORSMiddleware

from sqlalchemy.orm import Session

import models
import schemas

from database import (
    engine,
    get_db
)


# ============================================================
# DATABASE INITIALIZATION
# ============================================================

models.Base.metadata.create_all(
    bind=engine
)


# ============================================================
# FASTAPI
# ============================================================

app = FastAPI(
    title="LaneLogic API",
    version="2.0.0"
)


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# PRIORITY
# ============================================================

def priority_from_parked_space(
    parked_space_pct: float
):
    """
    Priority is based on PARKED vehicle space.

    This intentionally ignores moving vehicles and
    signal-waiting vehicles.

    < 5%    -> normal
    5-20%   -> low
    20-40%  -> moderate
    40-60%  -> high
    >=60%   -> critical
    """

    if parked_space_pct >= 60:
        return "critical", 4

    if parked_space_pct >= 40:
        return "high", 3

    if parked_space_pct >= 20:
        return "moderate", 2

    if parked_space_pct >= 5:
        return "low", 1

    return "normal", 0


# ============================================================
# ROADS
# ============================================================

@app.post(
    "/roads",
    response_model=schemas.RoadOut
)
def upsert_road(
    road: schemas.RoadCreate,
    db: Session = Depends(get_db)
):

    existing = db.get(
        models.Road,
        road.id
    )

    if existing:

        existing.name = road.name

        existing.latitude = road.latitude

        existing.longitude = road.longitude

        existing.polygon_geojson = (
            road.polygon_geojson
        )

        db.commit()

        db.refresh(existing)

        return existing

    new_road = models.Road(
        id=road.id,
        name=road.name,
        latitude=road.latitude,
        longitude=road.longitude,
        polygon_geojson=road.polygon_geojson
    )

    db.add(new_road)

    db.commit()

    db.refresh(new_road)

    return new_road


# ============================================================
# LIST ROADS
# ============================================================

@app.get(
    "/roads",
    response_model=List[schemas.RoadOut]
)
def list_roads(
    db: Session = Depends(get_db)
):

    return db.query(
        models.Road
    ).all()


# ============================================================
# ROAD DETAIL
# ============================================================

@app.get(
    "/roads/{road_id}",
    response_model=schemas.RoadDetailOut
)
def road_detail(
    road_id: str,
    db: Session = Depends(get_db)
):

    road = db.get(
        models.Road,
        road_id
    )

    if road is None:
        raise HTTPException(
            status_code=404,
            detail="Road not found"
        )

    recent_obs = (
        db.query(
            models.RoadWindowObservation
        )
        .filter(
            models.RoadWindowObservation.road_id
            == road_id
        )
        .order_by(
            models.RoadWindowObservation.window_index.desc()
        )
        .limit(20)
        .all()
    )

    chronic = (
        db.query(
            models.ChronicZone
        )
        .filter(
            models.ChronicZone.road_id
            == road_id
        )
        .first()
    )

    recommendations = (
        db.query(
            models.Recommendation
        )
        .filter(
            models.Recommendation.road_id
            == road_id
        )
        .order_by(
            models.Recommendation.priority_rank.asc()
        )
        .all()
    )

    return schemas.RoadDetailOut(
        road=road,
        recent_observations=recent_obs,
        chronic_zone=chronic,
        recommendations=recommendations
    )


# ============================================================
# HISTORY
# ============================================================

@app.get(
    "/roads/{road_id}/history",
    response_model=List[schemas.ObservationOut]
)
def road_history(
    road_id: str,
    db: Session = Depends(get_db)
):

    return (
        db.query(
            models.RoadWindowObservation
        )
        .filter(
            models.RoadWindowObservation.road_id
            == road_id
        )
        .order_by(
            models.RoadWindowObservation.window_index.asc()
        )
        .all()
    )


# ============================================================
# PERSON 1 DETECTIONS
# ============================================================

@app.post("/detections/bulk")
def ingest_detections(
    payload: schemas.DetectionsBulkIn,
    db: Session = Depends(get_db)
):

    if not payload.detections:
        return {
            "inserted": 0
        }

    # --------------------------------------------------------
    # Automatically create roads if needed.
    # This prevents the frontend/demo from depending on
    # manually seeded roads.
    # --------------------------------------------------------

    road_ids = {
        detection.road_id
        for detection in payload.detections
    }

    for road_id in road_ids:

        road = db.get(
            models.Road,
            road_id
        )

        if road is None:

            db.add(
                models.Road(
                    id=road_id,
                    name=road_id,
                    latitude=0.0,
                    longitude=0.0
                )
            )

    db.flush()

    rows = [
        models.VehicleDetection(
            **detection.model_dump()
        )
        for detection in payload.detections
    ]

    db.add_all(rows)

    db.commit()

    return {
        "inserted": len(rows),
        "roads_detected": list(road_ids)
    }


# ============================================================
# PERSON 2 ANALYSIS
# ============================================================

@app.post("/analysis/bulk")
def ingest_analysis(
    payload: schemas.ObservationsBulkIn,
    db: Session = Depends(get_db)
):

    if not payload.observations:
        return {
            "inserted": 0
        }

    rows = []

    affected_roads = {}

    # --------------------------------------------------------
    # Store Person 2 observations
    # --------------------------------------------------------

    for observation in payload.observations:

        data = observation.model_dump()

        # ----------------------------------------------------
        # Compatibility:
        #
        # If Person 2 hasn't yet added parked_space_pct,
        # use blocked_pct as the fallback.
        #
        # Once Person 2 is updated, blocked_pct will represent
        # parked-only space anyway.
        # ----------------------------------------------------

        if (
            data.get("parked_space_pct", 0.0) == 0.0
            and data.get("blocked_pct", 0.0) > 0.0
        ):
            data["parked_space_pct"] = data[
                "blocked_pct"
            ]

        if (
            data.get("parked_area_m2", 0.0) == 0.0
            and data.get("blocked_area_m2", 0.0) > 0.0
        ):
            data["parked_area_m2"] = data[
                "blocked_area_m2"
            ]

        if (
            data.get("parked_width_meters", 0.0) == 0.0
            and data.get(
                "equivalent_blocked_width_meters"
            ) is not None
        ):
            data["parked_width_meters"] = data[
                "equivalent_blocked_width_meters"
            ]

        rows.append(
            models.RoadWindowObservation(
                **data
            )
        )

        previous = affected_roads.get(
            observation.road_id
        )

        if (
            previous is None
            or observation.window_index
            > previous.window_index
        ):
            affected_roads[
                observation.road_id
            ] = observation

    # --------------------------------------------------------
    # Ensure roads exist
    # --------------------------------------------------------

    for road_id, observation in affected_roads.items():

        road = db.get(
            models.Road,
            road_id
        )

        if road is None:

            road = models.Road(
                id=road_id,
                name=road_id,
                latitude=0.0,
                longitude=0.0
            )

            db.add(road)

    db.flush()

    db.add_all(rows)

    # --------------------------------------------------------
    # Update current road status
    # --------------------------------------------------------

    for road_id, observation in affected_roads.items():

        road = db.get(
            models.Road,
            road_id
        )

        if road is None:
            continue

        parked_space_pct = float(
            getattr(
                observation,
                "parked_space_pct",
                0.0
            )
        )

        parked_width = float(
            getattr(
                observation,
                "parked_width_meters",
                0.0
            )
        )

        parked_area = float(
            getattr(
                observation,
                "parked_area_m2",
                0.0
            )
        )

        priority_level, priority_score = (
            priority_from_parked_space(
                parked_space_pct
            )
        )

        # ----------------------------------------------------
        # IMPORTANT:
        # Backend status is based on parked-space usage.
        # ----------------------------------------------------

        road.current_status = (
            priority_level
        )

        road.current_occupancy_pct = (
            observation.occupancy_pct
        )

        road.current_parked_space_pct = (
            parked_space_pct
        )

        road.current_parked_width_meters = (
            parked_width
        )

        road.current_parked_area_m2 = (
            parked_area
        )

        road.current_dominant_cause = (
            observation.cause
        )

        road.current_priority_score = (
            priority_score
        )

        road.current_priority_level = (
            priority_level
        )

    db.commit()

    return {
        "inserted": len(rows),
        "updated_roads": len(
            affected_roads
        )
    }


# ============================================================
# PERSON 4 - CHRONIC ZONES
# ============================================================

@app.post("/chronic-zones/bulk")
def ingest_chronic_zones(
    zones: List[schemas.ChronicZoneIn],
    db: Session = Depends(get_db)
):

    count = 0

    for zone in zones:

        existing = (
            db.query(
                models.ChronicZone
            )
            .filter(
                models.ChronicZone.road_id
                == zone.road_id
            )
            .first()
        )

        if existing:

            existing.dominant_cause = (
                zone.dominant_cause
            )

            existing.occurrence_count = (
                zone.occurrence_count
            )

            existing.severity_score = (
                zone.severity_score
            )

            existing.notes = (
                zone.notes
            )

        else:

            db.add(
                models.ChronicZone(
                    **zone.model_dump()
                )
            )

        road = db.get(
            models.Road,
            zone.road_id
        )

        if road:
            road.is_chronic = 1

        count += 1

    db.commit()

    return {
        "upserted": count
    }


# ============================================================
# CHRONIC ZONES
# ============================================================

@app.get(
    "/chronic-zones",
    response_model=List[
        schemas.ChronicZoneOut
    ]
)
def list_chronic_zones(
    db: Session = Depends(get_db)
):

    return (
        db.query(
            models.ChronicZone
        )
        .order_by(
            models.ChronicZone.severity_score.desc()
        )
        .all()
    )


# ============================================================
# PERSON 4 - RECOMMENDATIONS
# ============================================================

@app.post("/recommendations/bulk")
def ingest_recommendations(
    recs: List[schemas.RecommendationIn],
    db: Session = Depends(get_db)
):

    rows = [
        models.Recommendation(
            **recommendation.model_dump()
        )
        for recommendation in recs
    ]

    db.add_all(rows)

    db.commit()

    return {
        "inserted": len(rows)
    }


# ============================================================
# RECOMMENDATIONS
# ============================================================

@app.get(
    "/recommendations",
    response_model=List[
        schemas.RecommendationOut
    ]
)
def list_recommendations(
    road_id: Optional[str] = Query(
        default=None
    ),
    db: Session = Depends(get_db)
):

    query = db.query(
        models.Recommendation
    )

    if road_id:

        query = query.filter(
            models.Recommendation.road_id
            == road_id
        )

    return (
        query
        .order_by(
            models.Recommendation.priority_rank.asc()
        )
        .all()
    )


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/")
def root():

    return {
        "service": "LaneLogic API",
        "status": "ok",
        "version": "2.0.0"
    }